translations = {
    "apple": "яблоко",
    "asparagus": "спаржа",
    "avocado": "авокадо",
    "bacon": "бекон",
    "banana": "банан",
    "bean": "бобы",
    "beef": "говядина",
    "beer": "пиво",
    "beet": "свекла",
    "berry": "ягода",
    "boil-cheese": "плавленый сыр",
    "bread": "хлеб",
    "breadcrumbs": "панировочные сухари",
    "broccoli": "брокколи",
    "buckwheat": "гречка",
    "butter": "масло",
    "cabbage": "капуста",
    "canned-food": "консервы",
    "carrot": "морковь",
    "cauliflower": "цветная капуста",
    "caviar": "икра",
    "celery": "сельдерей",
    "cheese": "сыр",
    "cherry": "вишня",
    "chicken": "курица",
    "chocolate": "шоколад",
    "coconut": "кокос",
    "coffee": "кофе",
    "cognac": "коньяк",
    "condensed-milk": "сгущенное молоко",
    "cookie": "печенье",
    "corn": "кукуруза",
    "cottage-cheese": "творог",
    "crab": "краб",
    "cream": "сливки",
    "cucumber": "огурец",
    "dough": "тесто",
    "dried-fruits": "сухофрукт",
    "duck": "утка",
    "egg": "яйцо",
    "eggplant": "баклажан",
    "fennel": "фенхель",
    "fig": "инжир",
    "fish": "рыба",
    "flake": "хлопья",
    "flour": "мука",
    "garlic": "чеснок",
    "ginger": "имбирь",
    "grape": "виноград",
    "grapefruit": "грейпфрут",
    "ham": "ветчина",
    "honey": "мёд",
    "jam": "варенье",
    "juice": "сок",
    "ketchup": "кетчуп",
    "kiwi": "киви",
    "lemon": "лимон",
    "lentil": "чечевица",
    "lettuce": "салат",
    "mango": "манго",
    "mayo": "майонез",
    "meatball": "фарш",
    "melon": "дыня",
    "milk": "молоко",
    "millet": "просо",
    "mushroom": "гриб",
    "mustard": "горчица",
    "noodle": "макароны",
    "nut": "орех",
    "nutella": "нутелла",
    "oil": "растительное масло",
    "olives": "оливки",
    "onion": "лук",
    "orange": "апельсин",
    "oysters": "устрицы",
    "pate": "паштет",
    "pawpaw": "папайя",
    "pea": "горох",
    "peach": "персик",
    "pear": "груша",
    "pearl": "перловка",
    "pepper": "перец",
    "pickles": "маринованные огурцы",
    "pineapple": "ананас",
    "pomegranate": "гранат",
    "pork": "свинина",
    "potato": "картофель",
    "pumpkin": "тыква",
    "raddish": "редька",
    "rediska": "редис",
    "rib": "рёбра",
    "rice": "рис",
    "russian-green": "зелень",
    "ryazhenka": "ряженка",
    "salad": "салат",
    "salami": "колбаса",
    "salted-fish": "солёная рыба",
    "sausage": "сосиски",
    "semolina": "манка",
    "shrimp": "креветка",
    "sour cream": "сметана",
    "spinach": "шпинат",
    "spring onion": "зеленый лук",
    "squash": "кабачок",
    "squid": "кальмар",
    "strawberry": "клубника",
    "tartlets": "тарталетки",
    "tofu": "тофу",
    "tomato": "томат",
    "tortilla": "тортилья",
    "vasabi": "васаби",
    "yogurt-occluded": "йогурт",
    "zuccini": "кабачок"
}

template = '''
Ты получаешь на вход текст, из которого нужно получить строкой только ингредиенты и продукты питания. Обязательно нужно проверить текст на орфографию и исправить. Если в строке нет продуктов,
то напиши "Нет". Ты возвращаешь либо обработанный текст с продуктами, либо "Нет".\
\n\nТекущий разговор:\n{history}\nHuman: {input}\nAI:
'''

cont_types = ['audio', 'video', 'document', 'sticker', 'voice', 'location', 'contact']

reply = 'Аудио, видео и прочие форматы доступны только с платной подпиской!'